name: version_tracker
description: Local version and build tracker plugin. Provides the ability to keep track of previous installations and easily migrate data between upgrades.
version: 2.4.2
homepage: https://github.com/KevMorelli/version_tracker

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
